git rm	Godeps/_workspace/src/github.com/Microsoft/go-winio/LICENSE
git rm	Godeps/_workspace/src/github.com/Microsoft/go-winio/archive/tar/LICENSE
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/appProfile.json
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/client/contivModel.js
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/client/contivModelClient.go
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/client/contivModelClient.py
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/contivModel.go
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/endpointGroup.json
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/global.json
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/network.json
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/policy.json
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/rule.json
git rm	Godeps/_workspace/src/github.com/contiv/contivmodel/tenant.json
git rm	Godeps/_workspace/src/github.com/contiv/objdb/Godeps/Godeps.json
git rm	Godeps/_workspace/src/github.com/contiv/objdb/client.go
git rm	Godeps/_workspace/src/github.com/contiv/objdb/consulClient.go
git rm	Godeps/_workspace/src/github.com/contiv/objdb/etcdClient.go
git rm	Godeps/_workspace/src/github.com/contiv/objdb/etcdLock.go
git rm	Godeps/_workspace/src/github.com/contiv/objdb/etcdService.go
git rm	Godeps/_workspace/src/github.com/contiv/objdb/modeldb/modeldb.go
git rm	Godeps/_workspace/src/github.com/contiv/objdb/objdb.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/Makefile
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/fgraphFlow.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/fgraphTable.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofctrl/ofSwitch.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofnet.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofnetAgent.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofnetBgp.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofnetMaster.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofnetPolicy.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/ofnetSvcProxy.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/pqueue/pqueue.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/rpcHub/rpcHub.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/util.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/vlanBridge.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/vlrouter.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/vrouter.go
git rm	Godeps/_workspace/src/github.com/contiv/ofnet/vxlanBridge.go
git rm	Godeps/_workspace/src/github.com/contiv/vagrantssh/sshnode.go
git rm	Godeps/_workspace/src/github.com/contiv/vagrantssh/vagrant.go
git rm	Godeps/_workspace/src/github.com/contiv/vagrantssh/vagrantcommand.go
git rm	Godeps/_workspace/src/github.com/coreos/etcd/client/discover.go
git rm	Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/doc.go
git rm	Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/set.go
git rm	Godeps/_workspace/src/github.com/coreos/etcd/vendor/github.com/xiang90/probing/LICENSE
git rm	Godeps/_workspace/src/github.com/docker/distribution/vendor/github.com/Sirupsen/logrus/LICENSE
git rm	Godeps/_workspace/src/github.com/docker/distribution/vendor/github.com/bugsnag/bugsnag-go/LICENSE.txt
git rm	Godeps/_workspace/src/github.com/docker/distribution/vendor/github.com/bugsnag/panicwrap/LICENSE
git rm	Godeps/_workspace/src/github.com/docker/distribution/vendor/github.com/gorilla/context/LICENSE
git rm	Godeps/_workspace/src/github.com/docker/distribution/vendor/github.com/gorilla/mux/LICENSE
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/README.md
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/agent.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/api.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/catalog.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/health.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/kv.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/lock.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/semaphore.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/api/session.go
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/vendor/github.com/fsouza/go-dockerclient/LICENSE
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/vendor/github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus/LICENSE
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/vendor/github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp/LICENSE
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/go-msgpack/LICENSE
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/net-rpc-msgpackrpc/LICENSE.md
git rm	Godeps/_workspace/src/github.com/hashicorp/consul/vendor/github.com/ryanuber/columnize/COPYING
git rm	Godeps/_workspace/src/github.com/hashicorp/go-cleanhttp/README.md
git rm	Godeps/_workspace/src/github.com/hashicorp/serf/vendor/github.com/hashicorp/go-msgpack/LICENSE
git rm	Godeps/_workspace/src/github.com/samalba/dockerclient/dockerclient.go
git rm	Godeps/_workspace/src/github.com/samalba/dockerclient/example_responses.go
git rm	Godeps/_workspace/src/github.com/samalba/dockerclient/interface.go
git rm	Godeps/_workspace/src/github.com/samalba/dockerclient/mockclient/mock.go
git rm	Godeps/_workspace/src/github.com/samalba/dockerclient/nopclient/nop.go
git rm	Godeps/_workspace/src/github.com/samalba/dockerclient/types.go
git rm	Godeps/_workspace/src/github.com/shaleman/libOpenflow/openflow13/match.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/.travis.yml
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/Makefile
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/addr.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/addr_linux.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/link.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/link_linux.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/neigh_linux.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/netlink.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/nl/link_linux.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/nl/nl_linux.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/route.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/route_linux.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state.go
git rm	Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state_linux.go
git rm	Godeps/_workspace/src/golang.org/x/sys/unix/mkerrors.sh
git rm	Godeps/_workspace/src/golang.org/x/sys/unix/mksyscall.pl
git rm	Godeps/_workspace/src/golang.org/x/sys/unix/mksyscall_solaris.pl
git rm	Godeps/_workspace/src/gopkg.in/check.v1/LICENSE
git rm	Godeps/_workspace/src/gopkg.in/check.v1/README.md
git rm	Godeps/_workspace/src/gopkg.in/check.v1/benchmark.go
